version: "3.1"
services:
    db:
        image: rafacasti/proyectotarjetanfc:mysqlV5
        container_name: nfc_db
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: grancapitan
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
          tarjetaNFC:
            ipv4_address: 172.30.0.2
    www:
        image: rafacasti/proyectotarjetanfc:wwwV4
        container_name: kiosko
        ports: 
            - "80:80"
        links:
            - db
        volumes:
            - ./www:/var/www/html
        networks:
          tarjetaNFC:
            ipv4_address: 172.30.0.3
    phpmyadmin:
        image: rafacasti/proyectotarjetanfc:phpmyadminV2
        container_name: phpmyadmin_kiosko
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        networks:
          tarjetaNFC:
            ipv4_address: 172.30.0.4
volumes:
    persistent:
networks:
  tarjetaNFC:
    ipam:
      config:
        - subnet: "172.30.0.0/16"
          gateway: "172.30.0.1"
