version: "3.1"
services:
    db:
        image: rafacasti/proyectotarjetanfc:mysqlV1
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: grancapitan
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        image: rafacasti/proyectotarjetanfc:wwwV1 
        ports: 
            - "80:80"
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: rafacasti/proyectotarjetanfc:phpmyadminV1
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:
