version: "3"
services:
    db: 
        image: rafacasti/proyectotarjetanfc:v2
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: grancapitan
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_NATIVE_PASSWORD: 1234
        networks:
            - default
    www:
        image: rafacasti/proyectotarjetanfc:v2
        ports: 
            - "80:80"
        volumes:
            - /var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: rafacasti/proyectotarjetanfc:v2
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
volumes:
    persistent:
